FROM ibmcom/powerai:1.6.1-base-ubuntu18.04-py3

WORKDIR /workspace
RUN mkdir assets

COPY . .
RUN ["/bin/bash", "-c", "cd /opt/anaconda3/bin && source activate base && pip install --upgrade pip && pip install -r /workspace/requirements.txt" ]

#The following is required to get flask to work correctly on powerai-based images
RUN ["/bin/bash", "-c", "cd /opt/anaconda3/bin && source activate base && conda install werkzeug && export LC_ALL=C.UTF-8 && export LANG=C.UTF-8" ]
