FROM arm32v7/python:3.6.9-buster

# arm32v7 is the CPU that is integrated into Raspberry Pi 4

WORKDIR /workspace
RUN mkdir assets

COPY . .
RUN pip install --upgrade pip && pip install -r requirements.txt
